# Generated by Django 5.0.2 on 2025-12-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pcs', help_text='e.g., kg, liter, pcs, box', max_length=20),
        ),
    ]
